/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fisicamecanica;

/**
 *
 * @author daniel y maicol
 */
public class SemiParabolico extends javax.swing.JFrame {

    /**
     * Creates new form SemiParabolico
     */
    public SemiParabolico() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vi = new javax.swing.JTextField();
        vf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tiempo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Alturainicial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Vyfinal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Xmax = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(717, 579));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 210, 100, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Retornar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 500, 130, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Altura Inicial");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 110, 17);

        vi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viActionPerformed(evt);
            }
        });
        getContentPane().add(vi);
        vi.setBounds(130, 20, 132, 30);

        vf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vfActionPerformed(evt);
            }
        });
        getContentPane().add(vf);
        vf.setBounds(470, 360, 127, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("velocidad final");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 370, 110, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tiempo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 370, 70, 17);

        Tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoActionPerformed(evt);
            }
        });
        getContentPane().add(Tiempo);
        Tiempo.setBounds(160, 360, 132, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gravedad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 150, 90, 17);
        getContentPane().add(Alturainicial);
        Alturainicial.setBounds(130, 90, 132, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Velocidad en y final");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 420, 131, 17);

        Vyfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VyfinalActionPerformed(evt);
            }
        });
        getContentPane().add(Vyfinal);
        Vyfinal.setBounds(160, 410, 130, 30);

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULTADOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 260, 180, 42);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Distancia Total X");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 420, 120, 17);

        Xmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XmaxActionPerformed(evt);
            }
        });
        getContentPane().add(Xmax);
        Xmax.setBounds(470, 410, 127, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tierra", "Luna", "Marte", "Jupiter" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 140, 110, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/semiparabo.gif"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 80, 400, 270);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(590, -10, 110, 100);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Velocidad inicial");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 30, 110, 17);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fisica.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 720, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viActionPerformed

    private void vfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormulaSemiParabolico fsp = new FormulaSemiParabolico();

        fsp.vi = vi.getText();//se obtiene el numero que se escriba en la caja de texto
        fsp.Yi = Alturainicial.getText();//se obtiene el numero que se escriba en la caja de texto

        // en las siguientes condiciones se evalua la posicion del seleccion multiple  y de acuerdo a eso llevamos el valor de la gravedad  para que se pueda ejecutar las formulas
        if (jComboBox1.getSelectedIndex() == 0) {
            fsp.g = (float) 9.8;

        }
        if (jComboBox1.getSelectedIndex() == 1) {
            fsp.g = (float) 1.6;

        }
        if (jComboBox1.getSelectedIndex() == 2) {
            fsp.g = (float) 3.7;

        }
        if (jComboBox1.getSelectedIndex() == 3) {
            fsp.g = (float) 24.79;

        }
        // en las siguiente lineas se le colocan los resultados  que se traen de la clase Formula parabolico
        // con el Float.toString  transformamos un numero float a string para poder mostrarlo en la caja de texto
        Vyfinal.setText(Float.toString(fsp.VelocidadfinalY()) + " m/s");
        vf.setText(Float.toString(fsp.VelocidadFinal()) + " m/s");
        Tiempo.setText(Float.toString(fsp.Tiempo()) + " s");
        Xmax.setText(Float.toString(fsp.Xmax()) + " m");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoActionPerformed

    private void VyfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VyfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VyfinalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void XmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XmaxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemiParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemiParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemiParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemiParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SemiParabolico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alturainicial;
    private javax.swing.JTextField Tiempo;
    private javax.swing.JTextField Vyfinal;
    private javax.swing.JTextField Xmax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField vf;
    private javax.swing.JTextField vi;
    // End of variables declaration//GEN-END:variables
}
