/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fisicamecanica;



/**
 *
 * @author daniel y maicol
 */
public class TiroVertical extends javax.swing.JFrame {

    /**
     * Creates new form TiroVertical
     */
    public TiroVertical() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Alturaincial = new javax.swing.JTextField();
        Angulo = new javax.swing.JTextField();
        Velocidadinicial = new javax.swing.JTextField();
        AlturaMaxima = new javax.swing.JTextField();
        Tiempototal = new javax.swing.JTextField();
        DistanciaTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Vx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Vy = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        velocidadfinal = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Altura Inicial");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 22, 86, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gravedad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Velocidad Inicial");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 101, 130, 17);

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 260, 130, 42);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Altura Maxima");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 390, 140, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiempo total");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 440, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Distancia Total");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 480, 110, 17);
        getContentPane().add(Alturaincial);
        Alturaincial.setBounds(180, 19, 106, 30);
        getContentPane().add(Angulo);
        Angulo.setBounds(180, 57, 106, 30);
        getContentPane().add(Velocidadinicial);
        Velocidadinicial.setBounds(180, 95, 106, 30);
        getContentPane().add(AlturaMaxima);
        AlturaMaxima.setBounds(170, 380, 106, 30);

        Tiempototal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempototalActionPerformed(evt);
            }
        });
        getContentPane().add(Tiempototal);
        Tiempototal.setBounds(170, 430, 106, 30);
        getContentPane().add(DistanciaTotal);
        DistanciaTotal.setBounds(170, 470, 106, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 210, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Velocidad en X");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 390, 110, 17);
        getContentPane().add(Vx);
        Vx.setBounds(440, 380, 106, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Velocidad en Y");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 440, 130, 17);
        getContentPane().add(Vy);
        Vy.setBounds(440, 430, 106, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Retornar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 530, 87, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Velocidad final");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 480, 120, 17);

        velocidadfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velocidadfinalActionPerformed(evt);
            }
        });
        getContentPane().add(velocidadfinal);
        velocidadfinal.setBounds(440, 470, 106, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tierra", "Luna", "Marte", "Jupiter" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 150, 110, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tiro.gif"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 80, 400, 290);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(610, -10, 110, 110);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Angulo");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 63, 110, 17);
        getContentPane().add(tiempo);
        tiempo.setBounds(620, 380, 90, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tiempo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(560, 390, 51, 17);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fisica.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 790, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormulasTirovertical ft = new FormulasTirovertical();
        ft.angulo = Angulo.getText();//se obtiene el numero que se escriba en la caja de texto
        ft.vi = Velocidadinicial.getText();//se obtiene el numero que se escriba en la caja de texto
        ft.yi = Alturaincial.getText();//se obtiene el numero que se escriba en la caja de texto
        
        // en las siguientes condiciones se evalua la posicion del seleccion multiple  y de acuerdo a eso llevamos el valor de la gravedad  para que se pueda ejecutar las formulas
        if (jComboBox1.getSelectedIndex() == 0) {
            ft.g = (float) 9.8;

        }
        if (jComboBox1.getSelectedIndex() == 1) {
            ft.g = (float) 1.6;

        }
        if (jComboBox1.getSelectedIndex() == 2) {
            ft.g = (float) 3.7;

        }
        if (jComboBox1.getSelectedIndex() == 3) {
            ft.g = (float) 24.79;

        }
        // en las siguiente lineas se le colocan los resultados  que se traen de la clase Formula parabolico
        // con el Float.toString  transformamos un numero float a string para poder mostrarlo en la caja de texto
        Tiempototal.setText(Float.toString(ft.Tiempo()) + " s");
        AlturaMaxima.setText(Float.toString(ft.alturaMaxima()) + " m");
        DistanciaTotal.setText(Float.toString(ft.DistanciaTotal()) + " m");
        Vx.setText(Float.toString(ft.VelocidadenX()) + " m/s");
        Vy.setText(Float.toString(ft.VelocidadenY()) + " m/s");
        velocidadfinal.setText(Float.toString(ft.Velocidadfinal()) + " m/s");
        tiempo.setText(Float.toString(ft.tiempoamitad()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TiempototalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempototalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempototalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void velocidadfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidadfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidadfinalActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiroVertical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiroVertical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiroVertical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiroVertical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiroVertical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaMaxima;
    private javax.swing.JTextField Alturaincial;
    private javax.swing.JTextField Angulo;
    private javax.swing.JTextField DistanciaTotal;
    private javax.swing.JTextField Tiempototal;
    private javax.swing.JTextField Velocidadinicial;
    private javax.swing.JTextField Vx;
    private javax.swing.JTextField Vy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tiempo;
    private javax.swing.JTextField velocidadfinal;
    // End of variables declaration//GEN-END:variables
}
