/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fisicamecanica;


/**
 *
 * @author daniel , maicol
 */
public class Parabolico extends javax.swing.JFrame {

    /**
     * Creates new form Parabolico
     */
    public Parabolico() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tiempodevuelo = new javax.swing.JTextField();
        Velocidadinicial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Angulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TiempoenYmax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AlturaMaxima = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AlcanceHorizontal = new javax.swing.JTextField();
        Retornar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fisica cuantica.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 597));
        getContentPane().setLayout(null);

        Calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular);
        Calcular.setBounds(70, 250, 100, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiempo de vuelo Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 410, 170, 17);

        Tiempodevuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempodevueloActionPerformed(evt);
            }
        });
        getContentPane().add(Tiempodevuelo);
        Tiempodevuelo.setBounds(270, 390, 132, 30);

        Velocidadinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadinicialActionPerformed(evt);
            }
        });
        getContentPane().add(Velocidadinicial);
        Velocidadinicial.setBounds(190, 30, 132, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tiempo en Alcanzar Altura Maxima");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 470, 250, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Velocidad Inicial en m/s");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 200, 17);

        Angulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnguloActionPerformed(evt);
            }
        });
        getContentPane().add(Angulo);
        Angulo.setBounds(190, 90, 132, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Respuestas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 290, 230, 47);
        getContentPane().add(TiempoenYmax);
        TiempoenYmax.setBounds(270, 460, 132, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Altura Maxima Y");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 400, 120, 17);

        AlturaMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaMaximaActionPerformed(evt);
            }
        });
        getContentPane().add(AlturaMaxima);
        AlturaMaxima.setBounds(600, 390, 132, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alcance Horizontal X");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 470, 170, 17);

        AlcanceHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcanceHorizontalActionPerformed(evt);
            }
        });
        getContentPane().add(AlcanceHorizontal);
        AlcanceHorizontal.setBounds(600, 460, 132, 30);

        Retornar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Retornar.setText("Retornar");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });
        getContentPane().add(Retornar);
        Retornar.setBounds(320, 530, 110, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tierra", "Luna", "Marte", "Jupiter" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 150, 100, 47);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gravedad");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 160, 80, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parabolico.gif"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 100, 400, 260);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Angulo");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 100, 58, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(610, 0, 120, 100);

        jLabel15.setBackground(new java.awt.Color(51, 51, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fisica.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 800, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        FormulaParabolico F = new FormulaParabolico();
        F.vi = Velocidadinicial.getText();//se obtiene el numero que se escriba en la caja de texto
        F.an = Angulo.getText();//se obtiene el numero que se escriba en la caja de texto
        // en las siguientes condiciones se evalua la posicion del seleccion multiple  y de acuerdo a eso llevamos el valor de la gravedad  para que se pueda ejecutar las formulas
        if (jComboBox1.getSelectedIndex() == 0) {
            F.g = (float) 9.8;

        }
        if (jComboBox1.getSelectedIndex() == 1) {
            F.g = (float) 1.6;

        }
        if (jComboBox1.getSelectedIndex() == 2) {
            F.g = (float) 3.7;

        }
        if (jComboBox1.getSelectedIndex() == 3) {
            F.g = (float) 24.79;

        }
        // en las siguiente lineas se le colocan los resultados  que se traen de la clase Formula parabolico
        // con el Float.toString  transformamos un numero float a string para poder mostrarlo en la caja de texto
        Tiempodevuelo.setText(Float.toString(F.Tiempodevuelototal()) + " s");
        TiempoenYmax.setText(Float.toString(F.tiempoenalcanzaralturamaxima()) + " s");
        AlturaMaxima.setText(Float.toString(F.alturaMaxima()) + " m");
        AlcanceHorizontal.setText(Float.toString(F.AlcanceHotizontal()) + " m");

    }//GEN-LAST:event_CalcularActionPerformed

    private void TiempodevueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempodevueloActionPerformed

    }//GEN-LAST:event_TiempodevueloActionPerformed

    private void VelocidadinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadinicialActionPerformed

    }//GEN-LAST:event_VelocidadinicialActionPerformed

    private void AnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnguloActionPerformed

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RetornarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AlcanceHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcanceHorizontalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlcanceHorizontalActionPerformed

    private void AlturaMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaMaximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parabolico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlcanceHorizontal;
    private javax.swing.JTextField AlturaMaxima;
    private javax.swing.JTextField Angulo;
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Retornar;
    private javax.swing.JTextField Tiempodevuelo;
    private javax.swing.JTextField TiempoenYmax;
    private javax.swing.JTextField Velocidadinicial;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
